### ISSUE TITLE
Write a code of conduct

### ISSUE THREAD

**Issue by megoth** [solid/solid.mit.edu#19]
To show the willingness of inclusiveness and setting up some basic social guidelines for the community, might it be interesting to have a code of conduct?

Some links for Inspiration:
* [Code for America's Code of Conduct](https://github.com/codeforamerica/codeofconduct)
* [Python Community Code of Conduct](https://www.python.org/psf/codeofconduct/)
* [The Technology Transformation Service Code of Conduct](https://github.com/18F/code-of-conduct)
* [Code of Conduct for Design Systems Slack](http://design.systems/slack/)
* [HOWTO design a code of conduct for your community](https://adainitiative.org/2014/02/18/howto-design-a-code-of-conduct-for-your-community/)

**Comment by RubenVerborgh** [comment]
@amyvdh compiled a good code of conduct a while ago. We should indeed add it.

**Comment by megoth** [comment]
I should be more explicit than a reaction to your comment =P 

But yeah, that sounds awesome ^_^

I'll leave this issue open until it's added.

**Comment by megoth** [comment]
As this is available on https://github.com/solid/community/blob/master/code-of-conduct.md, I'm closing this.
