### ISSUE TITLE
Clarify the relation between this website and solidproject.org

### ISSUE THREAD

**Issue by NSeydoux** [solid/solid.mit.edu#29]
Some community members are confused by the existence of two entry points into the Solid ecosystem: this page, and solidproject.org. The relationship between the two should be clarified: a current proposal by @timbl is to add a banner at the top of the page with the following text: "This is the historical site for the Solid project, when it was incepted at MIT. The Solid project's homepage is now hosted at https://solidproject.org/"

**Comment by Mitzi-Laszlo** [comment]
https://github.com/solid/solid.mit.edu/pull/30

**Comment by justinwb** [comment]
@NSeydoux i don't believe that what's submitted in #30 or #31 will work on the production site given the conditionals around it. can you revise and resubmit?

**Comment by NSeydoux** [comment]
I will try to get to it today

**Comment by justinwb** [comment]
@NSeydoux this has been deployed to solid.mit.edu.
