### ISSUE TITLE
http://solid.mit.edu not working

### ISSUE THREAD

**Issue by mediaprophet** [solid/solid.mit.edu#8]
simple fix i'm sure.

**Comment by almereyda** [comment]
Yes, a request to the site yields

    Failed to connect to solid.mit.edu port 80: Connection refused

**Comment by almereyda** [comment]
`timbl` wrote in https://gitter.im/solid/chat

> Hi Jon — try https://solid.mit.edu/
> You know we are trying to get everyone to use Https ;-)
> We do need a redirect from port 80

**Comment by mediaprophet** [comment]
fixed.
