### ISSUE TITLE
Mixed content breaks site on android

### ISSUE THREAD

**Issue by melvincarvalho** [solid/solid.mit.edu#9]
Here is a screenshot I was sent.  Uploading the image and serving it over HTTPS will likely fix the issue.

![solidmit](https://user-images.githubusercontent.com/65864/35321294-eb49a95a-00e6-11e8-8ee3-aee8f7358a71.png)

**Comment by melvincarvalho** [comment]
Note this has wider implication for solid mashups with mixed content on mobile.  For example if you have a friend whose avatar is served over http it may be break an app on android.

This could also be a contrived attack vector.

**Comment by almereyda** [comment]
Mixed Content is also responsible for not marking the scheme green in the browser bar of desktop clients.

We are talking about http://sc1.qcri.org/cop18/figs/qcri_logo.png

**Comment by melvincarvalho** [comment]
Using

https://www.browserling.com/browse/android/7.1/https%3A%2F%2Fsolid.mit.edu%2F

![browserling](https://user-images.githubusercontent.com/65864/36114738-2e06abf4-1031-11e8-8afa-b9f96dbba583.png)
![certdetails](https://user-images.githubusercontent.com/65864/36114744-2fbaed84-1031-11e8-9b26-12f9cb98c62a.png)
![certview](https://user-images.githubusercontent.com/65864/36114747-3194e894-1031-11e8-8b9a-d81c417b5a8f.png)

**Comment by melvincarvalho** [comment]
Site now passes on browserling, closing
